FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/
COPY imperative/target/*-runner /work/server-test-application
RUN chmod 775 -R /work
CMD ["./server-test-application", "-Dquarkus.http.host=0.0.0.0"]