{
 "title": "Quarkus JVM",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(base_memory_usedHeap_bytes)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(base_memory_committedHeap_bytes)",
     "legendFormat": "Commited"
    },
    { "expr": "sum(base_memory_maxHeap_bytes)", "legendFormat": "Max" }
   ]
  },
  {
   "title": "Total Non-Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_memory_usedNonHeap_bytes)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(vendor_memory_committedNonHeap_bytes)",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Eden Space (Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memoryPool_usage_bytes{name=\"Eden Space\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "vendor_memoryPool_usage_max_bytes{name=\"Eden Space\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Survivor Space (Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memoryPool_usage_bytes{name=\"Survivor Space\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "vendor_memoryPool_usage_max_bytes{name=\"Survivor Space\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Old Generation (Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memoryPool_usage_bytes{name=\"Tenured Gen\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "vendor_memoryPool_usage_max_bytes{name=\"Tenured Gen\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Metaspace (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memoryPool_usage_bytes{name=\"Metaspace\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "vendor_memoryPool_usage_max_bytes{name=\"Metaspace\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Compressed Class Space (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memoryPool_usage_bytes{name=\"Compressed Class Space\"}",
     "legendFormat": "Used - {{instance_label}}"
    },
    {
     "expr": "vendor_memoryPool_usage_max_bytes{name=\"Compressed Class Space\"}",
     "legendFormat": "Max - {{instance_label}}"
    }
   ]
  },
  {
   "title": "CodeHeap 'profiled nmethods' (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memoryPool_usage_bytes{name=\"CodeHeap 'profiled nmethods'\"}",
     "legendFormat": "Used - {{instance_label}}"
    },
    {
     "expr": "vendor_memoryPool_usage_max_bytes{name=\"CodeHeap 'profiled nmethods'\"}",
     "legendFormat": "Max - {{instance_label}}"
    }
   ]
  },
  {
   "title": "CodeHeap 'non-profiled nmethods' (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memoryPool_usage_bytes{name=\"CodeHeap 'non-profiled nmethods'\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "vendor_memoryPool_usage_max_bytes{name=\"CodeHeap 'non-profiled nmethods'\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "CodeHeap 'non-nmethods' (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memoryPool_usage_bytes{name=\"CodeHeap 'non-nmethods'\"} ",
     "legendFormat": "Used"
    },
    {
     "expr": "vendor_memoryPool_usage_max_bytes{name=\"CodeHeap 'non-nmethods'\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "GC Count (Minor / Major)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "increase(base_gc_total{name=\"Copy\"}[15s])",
     "legendFormat": "Minor GC"
    },
    {
     "expr": "increase(base_gc_total{name=\"MarkSweepCompact\"}[15s])",
     "legendFormat": "Major GC"
    }
   ]
  },
  {
   "title": "System Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "base_cpu_systemLoadAverage", "legendFormat": "System Average Loade" },
    { "expr": "base_cpu_availableProcessors", "legendFormat": "CPU Size" }
   ]
  },
  {
   "title": "GC Pause Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(base_gc_time_total_seconds{name=\"MarkSweepCompact\"}[1m])/rate(base_gc_total{name=\"MarkSweepCompact\"}[1m])",
     "legendFormat": "Old Generation"
    },
    {
     "expr": "rate(base_gc_time_total_seconds{name=\"Copy\"}[1m])/rate(base_gc_total{name=\"Copy\"}[1m])",
     "legendFormat": "Young Generation"
    }
   ]
  },
  {
   "title": "Classes Unloaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_classloader_loadedClasses_count",
     "legendFormat": "Loaded Classes - Current"
    },
    {
     "expr": "base_classloader_unloadedClasses_total",
     "legendFormat": "Unloaded Classes - Total"
    }
   ]
  },
  {
   "title": "Threads (Deamon/Live)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "base_thread_daemon_count", "legendFormat": "Only Deamon" },
    { "expr": "base_thread_count", "legendFormat": "All Live" }
   ]
  }
 ]
}