{
 "title": "Quarkus Native",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(base_memory_usedHeap_bytes)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(base_memory_committedHeap_bytes)",
     "legendFormat": "Commited"
    }
   ]
  },
  {
   "title": "Total Non-Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_memory_usedNonHeap_bytes)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(vendor_memory_committedNonHeap_bytes)",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "GC Count (Young / Complete)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "increase(base_gc_total{name=\"young generation scavenger\"}[15s])",
     "legendFormat": "Young GC"
    },
    {
     "expr": "increase(base_gc_total{name=\"complete scavenger\"}[15s])",
     "legendFormat": "Complete GC"
    }
   ]
  },
  {
   "title": "GC Pause Time (Young / Complete)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(base_gc_time_total_seconds{name=\"complete scavenger\"}[15s])/rate(base_gc_total{name=\"complete scavenger\"}[15s])",
     "legendFormat": "Complete"
    },
    {
     "expr": "rate(base_gc_time_total_seconds{name=\"young generation scavenger\"}[15s])/rate(base_gc_total{name=\"young generation scavenger\"}[15s])",
     "legendFormat": "Young"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "base_thread_count", "legendFormat": "All Live" }
   ]
  },
  {
   "title": "System Load Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "base_cpu_systemLoadAverage", "legendFormat": "System Average Loade" },
    { "expr": "base_cpu_availableProcessors", "legendFormat": "CPU Size" }
   ]
  }
 ]
}